# Generated by Django 4.2.7 on 2024-02-14 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='MPSI 1 -- 2023-2024')),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='Divers')),
            ],
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(default='')),
                ('etoiles', models.IntegerField(default=1)),
                ('enonce', models.TextField(default='')),
                ('dataFunc', models.TextField(default='def dataFunc(seed):\n    rd.seed(seed)\n    data={}\n    return data')),
                ('testFunc', models.TextField(default='def testFunc(data, reponse):\n    return True')),
                ('solution', models.TextField(default='')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challengeMPSI.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('estClasse', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challengeMPSI.classe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Succes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeMPSI.etudiant')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeMPSI.epreuve')),
            ],
        ),
    ]
