# Generated by Django 4.2.7 on 2024-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='domaine',
            name='image',
            field=models.ImageField(default='images/defaultDomaine.png', upload_to='images'),
        ),
    ]
