# Generated by Django 4.2.7 on 2024-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0002_domaine_description_domaine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
