# Generated by Django 4.2.7 on 2024-02-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0003_domaine_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='succes',
            old_name='mission',
            new_name='epreuve',
        ),
    ]
