# Generated by Django 4.2.7 on 2024-03-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0004_rename_mission_succes_epreuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='solution',
            field=models.TextField(default="Pas de solution pour l'instant"),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='testFunc',
            field=models.TextField(default='def testFunc(data, reponse):\n    rep = float(reponse)\n    return np.abs((rep-repOK)/repOK)<1e-3'),
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='Chapitre 1')),
                ('numero', models.IntegerField(default=0)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeMPSI.domaine')),
            ],
        ),
        migrations.AddField(
            model_name='epreuve',
            name='chapitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='challengeMPSI.chapitre'),
        ),
    ]
