# Generated by Django 4.2.11 on 2024-05-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0005_alter_epreuve_solution_alter_epreuve_testfunc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='image',
            field=models.TextField(default='optique.png'),
        ),
    ]
