# Generated by Django 4.2.11 on 2024-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0006_alter_domaine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='nom_affiche',
            field=models.TextField(default='Divers'),
        ),
    ]
