# Generated by Django 4.0.6 on 2025-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0007_domaine_nom_affiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='spe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classe',
            name='spe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='succes',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
