# Generated by Django 4.0.6 on 2025-12-05 19:48

import challengeMPSI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challengeMPSI', '0008_chapitre_spe_classe_spe_alter_succes_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=challengeMPSI.models.image_path)),
                ('imageDomaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='challengeMPSI.domaine')),
            ],
        ),
    ]
